import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Activity, CalendarClock, ClipboardList, Pencil, Plus, RefreshCw, Search, Settings2 } from "lucide-react";
import { toast } from "sonner";
import type { ActivityPriority, ActivityTemplate, ActivityTemplateOwnerRole, ActivityTemplateRecurrence } from "../../../shared/types";
import DeliveryTemplateCatalog from "./DeliveryTemplateCatalog";
import DeliveryArchivePanel from "./DeliveryArchivePanel";

const priorities: ActivityPriority[] = ["Baixa", "Média", "Alta", "Crítica"];
const weekdays = [{ value: 1, label: "Segunda-feira" }, { value: 2, label: "Terça-feira" }, { value: 3, label: "Quarta-feira" }, { value: 4, label: "Quinta-feira" }, { value: 5, label: "Sexta-feira" }, { value: 6, label: "Sábado" }, { value: 0, label: "Domingo" }];
const roleLabels: Record<ActivityTemplateOwnerRole, string> = { manager: "GP do projeto", technical_lead: "Líder técnico", consultant: "Consultor" };
const gpPhases = ["Discover", "Prepare", "Explore", "Realize", "Deploy", "Run"] as const;

type ActivityForm = Omit<ActivityTemplate, "id" | "createdByUserId" | "createdAt" | "updatedAt"> & { selectedProjectIds: string[] };
const emptyActivity = (): ActivityForm => ({ title: "", description: "", priority: "Média", recurrence: "none", weekday: 5, monthDay: 1, dueOffsetDays: 0, ownerRole: "manager", gpPhase: "Prepare", required: true, appliesToAllProjects: true, active: true, projects: [], selectedProjectIds: [] });
type BdcqForm = { id: string; question: string; category: string; modules: string[]; scopeItemKeys: string[]; required: boolean; active: number };
const emptyBdcq = (): BdcqForm => ({ id: "", question: "", category: "", modules: [], scopeItemKeys: [], required: true, active: 1 });
type ConfigurationForm = { id: string; description: string; category: string; modules: string[]; scopeItemKeys: string[]; active: boolean };
const emptyConfiguration = (): ConfigurationForm => ({ id: "", description: "", category: "Configuração", modules: [], scopeItemKeys: [], active: true });

export default function StandardConfigurations() {
  const utils = trpc.useUtils();
  const { data: activityTemplates = [] } = trpc.activities.templates.list.useQuery();
  const { data: activityOptions = [] } = trpc.activities.templates.options.useQuery();
  const { data: bdcqTemplates = [] } = trpc.workflow.bdcq.templates.list.useQuery();
  const { data: bdcqOptions = [] } = trpc.workflow.bdcq.templates.options.useQuery();
  const { data: configurationTemplates = [] } = trpc.workflow.configurations.templates.list.useQuery();
  const { data: lookups } = trpc.settings.getLookups.useQuery();
  const [activityOpen, setActivityOpen] = useState(false);
  const [editingActivityId, setEditingActivityId] = useState("");
  const [activityForm, setActivityForm] = useState<ActivityForm>(emptyActivity);
  const [bdcqOpen, setBdcqOpen] = useState(false);
  const [bdcqForm, setBdcqForm] = useState<BdcqForm>(emptyBdcq);
  const [bdcqSearch, setBdcqSearch] = useState("");
  const [configurationOpen, setConfigurationOpen] = useState(false);
  const [configurationForm, setConfigurationForm] = useState<ConfigurationForm>(emptyConfiguration);
  const [configurationSearch, setConfigurationSearch] = useState("");

  const refreshActivities = async () => { await utils.activities.templates.invalidate(); };
  const createActivity = trpc.activities.templates.create.useMutation({ onSuccess: async () => { await refreshActivities(); setActivityOpen(false); toast.success("Atividade padrão criada"); }, onError: error => toast.error(error.message) });
  const updateActivity = trpc.activities.templates.update.useMutation({ onSuccess: async () => { await refreshActivities(); setActivityOpen(false); toast.success("Atividade padrão atualizada"); }, onError: error => toast.error(error.message) });
  const setActivityActive = trpc.activities.templates.setActive.useMutation({ onSuccess: refreshActivities, onError: error => toast.error(error.message) });
  const syncActivities = trpc.activities.templates.sync.useMutation({ onSuccess: data => { toast.success(`${data.created} atividades criadas e ${data.updated} atualizadas`); }, onError: error => toast.error(error.message) });
  const refreshBdcq = async () => { await utils.workflow.bdcq.templates.invalidate(); };
  const createBdcq = trpc.workflow.bdcq.templates.create.useMutation({ onSuccess: async () => { await refreshBdcq(); setBdcqOpen(false); toast.success("Pergunta padrão criada"); }, onError: error => toast.error(error.message) });
  const updateBdcq = trpc.workflow.bdcq.templates.update.useMutation({ onSuccess: async () => { await refreshBdcq(); setBdcqOpen(false); toast.success("Pergunta padrão atualizada"); }, onError: error => toast.error(error.message) });
  const refreshConfigurations = async () => { await utils.workflow.configurations.templates.invalidate(); };
  const createConfiguration = trpc.workflow.configurations.templates.create.useMutation({ onSuccess: async () => { await refreshConfigurations(); setConfigurationOpen(false); toast.success("Modelo de configuração criado"); }, onError: error => toast.error(error.message) });
  const updateConfiguration = trpc.workflow.configurations.templates.update.useMutation({ onSuccess: async () => { await refreshConfigurations(); setConfigurationOpen(false); toast.success("Modelo de configuração atualizado"); }, onError: error => toast.error(error.message) });

  const moduleOptions = [...new Set([...(lookups?.fronts || []).filter(item => item.active).map(item => item.value), ...bdcqOptions.map(item => item.module)])].filter(Boolean).sort();
  const filteredBdcq = useMemo(() => bdcqTemplates.filter(template => [template.question, template.category, ...(template.modules || []), ...(template.scopeItemKeys || [])].join(" ").toLocaleLowerCase("pt-BR").includes(bdcqSearch.toLocaleLowerCase("pt-BR"))), [bdcqTemplates, bdcqSearch]);
  const filteredConfigurations = useMemo(() => configurationTemplates.filter(template => [template.description, template.category, ...(template.modules || []), ...(template.scopeItemKeys || [])].join(" ").toLocaleLowerCase("pt-BR").includes(configurationSearch.toLocaleLowerCase("pt-BR"))), [configurationTemplates, configurationSearch]);
  const toggle = (values: string[], value: string) => values.includes(value) ? values.filter(item => item !== value) : [...values, value];

  const openNewActivity = () => { const form = emptyActivity(); form.selectedProjectIds = activityOptions.map(option => option.project.id); form.projects = activityOptions.map(option => ({ projectId: option.project.id, assigneeUserId: "" })); setEditingActivityId(""); setActivityForm(form); setActivityOpen(true); };
  const openActivity = (template: ActivityTemplate) => { setEditingActivityId(template.id); setActivityForm({ ...template, projects: template.projects, selectedProjectIds: template.appliesToAllProjects ? activityOptions.map(option => option.project.id) : template.projects.map(item => item.projectId) }); setActivityOpen(true); };
  const saveActivity = () => {
    const projectMap = new Map(activityForm.projects.map(item => [item.projectId, item.assigneeUserId]));
    const projectIds = activityForm.appliesToAllProjects ? activityOptions.map(option => option.project.id) : activityForm.selectedProjectIds;
    const data = { ...activityForm, projects: projectIds.map(projectId => ({ projectId, assigneeUserId: projectMap.get(projectId) || "" })) };
    delete (data as Partial<ActivityForm>).selectedProjectIds;
    if (editingActivityId) updateActivity.mutate({ id: editingActivityId, data });
    else createActivity.mutate(data);
  };

  const openBdcq = (template?: any) => { setBdcqForm(template ? { id: template.id, question: template.question, category: template.category || "", modules: template.modules || [], scopeItemKeys: template.scopeItemKeys || [], required: Boolean(template.required), active: template.active ?? 1 } : emptyBdcq()); setBdcqOpen(true); };
  const saveBdcq = () => {
    const data = { question: bdcqForm.question, category: bdcqForm.category, modules: bdcqForm.modules, scopeItemKeys: bdcqForm.scopeItemKeys, required: bdcqForm.required, active: bdcqForm.active };
    if (bdcqForm.id) updateBdcq.mutate({ id: bdcqForm.id, data }); else createBdcq.mutate(data);
  };
  const openConfiguration = (template?: any) => { setConfigurationForm(template ? { id: template.id, description: template.description, category: template.category || "Configuração", modules: template.modules || [], scopeItemKeys: template.scopeItemKeys || [], active: template.active !== false && template.active !== 0 } : emptyConfiguration()); setConfigurationOpen(true); };
  const saveConfiguration = () => { const { id, ...data } = configurationForm; if (id) updateConfiguration.mutate({ id, data }); else createConfiguration.mutate(data); };

  return <div className="space-y-6">
    <div><h1 className="text-2xl font-bold">Configurações do Tech</h1><p className="text-sm text-muted-foreground">Modelos globais que orientam a execução completa dos projetos.</p></div>
    <Tabs defaultValue="master-trail" className="space-y-4">
      <TabsList className="grid h-auto w-full max-w-5xl grid-cols-2 sm:grid-cols-4"><TabsTrigger value="master-trail">Trilha Mestre</TabsTrigger><TabsTrigger value="activities">Atividades padrão</TabsTrigger><TabsTrigger value="bdcq">Perguntas BDCQ</TabsTrigger><TabsTrigger value="configurations">Modelos de configuração</TabsTrigger></TabsList>
      <TabsContent value="master-trail" className="space-y-4">
        <DeliveryTemplateCatalog moduleOptions={moduleOptions} scopeOptions={bdcqOptions} projectOptions={activityOptions.map(option => option.project)} />
        <DeliveryArchivePanel />
      </TabsContent>
      <TabsContent value="activities" className="space-y-4">
        <div className="flex flex-col gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={() => syncActivities.mutate()} disabled={syncActivities.isPending}><RefreshCw className="mr-2 h-4 w-4" />Sincronizar</Button><Button onClick={openNewActivity}><Plus className="mr-2 h-4 w-4" />Nova atividade padrão</Button></div>
        <div className="grid gap-3 lg:grid-cols-2">{activityTemplates.map(template => <Card key={template.id} className={!template.active ? "opacity-60" : ""}><CardHeader className="pb-2"><div className="flex items-start justify-between gap-3"><CardTitle className="text-base">{template.title}</CardTitle><Switch checked={template.active} onCheckedChange={active => setActivityActive.mutate({ id: template.id, active })} /></div></CardHeader><CardContent className="space-y-3"><p className="line-clamp-2 text-sm text-muted-foreground">{template.description || "Sem descrição"}</p><div className="flex flex-wrap gap-1.5"><Badge>{template.priority}</Badge><Badge variant="secondary">Fase {template.gpPhase || "Prepare"}</Badge><Badge variant={template.required ? "default" : "outline"}>{template.required ? "Obrigatória" : "Opcional"}</Badge><Badge variant="outline">{template.recurrence === "none" ? `${template.dueOffsetDays} dias após início` : template.recurrence === "weekly" ? `Semanal · ${weekdays.find(day => day.value === template.weekday)?.label}` : `Mensal · dia ${template.monthDay}`}</Badge><Badge variant="secondary">{roleLabels[template.ownerRole]}</Badge><Badge variant="outline">{template.appliesToAllProjects ? "Todos os projetos" : `${template.projects.length} projetos`}</Badge></div><Button variant="outline" size="sm" onClick={() => openActivity(template)}><Pencil className="mr-2 h-3.5 w-3.5" />Editar</Button></CardContent></Card>)}{activityTemplates.length === 0 && <Empty label="Nenhuma atividade padrão cadastrada." />}</div>
      </TabsContent>
      <TabsContent value="bdcq" className="space-y-4">
        <div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar pergunta, módulo ou scope item" value={bdcqSearch} onChange={event => setBdcqSearch(event.target.value)} /></div><Button onClick={() => openBdcq()}><Plus className="mr-2 h-4 w-4" />Nova pergunta padrão</Button></div>
        <div className="space-y-2">{filteredBdcq.map((template: any) => <Card key={template.id} className={template.active === 0 ? "opacity-60" : ""}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-medium">{template.question}</p><div className="mt-2 flex flex-wrap gap-1.5"><Badge variant={template.required ? "default" : "secondary"}>{template.required ? "Obrigatória" : "Opcional"}</Badge>{template.category && <Badge variant="secondary">{template.category}</Badge>}{!template.modules?.length && !template.scopeItemKeys?.length && <Badge variant="outline">Pergunta geral</Badge>}{template.modules?.map((module: string) => <Badge key={module} variant="outline">{module}</Badge>)}{template.scopeItemKeys?.map((key: string) => <Badge key={key} className="bg-blue-50 text-blue-800">Scope: {key}</Badge>)}</div></div><Button variant="outline" size="sm" onClick={() => openBdcq(template)}><Pencil className="mr-2 h-3.5 w-3.5" />Editar</Button></CardContent></Card>)}{filteredBdcq.length === 0 && <Empty label="Nenhuma pergunta encontrada." />}</div>
      </TabsContent>
      <TabsContent value="configurations" className="space-y-4">
        <div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar modelo, módulo ou scope item" value={configurationSearch} onChange={event => setConfigurationSearch(event.target.value)} /></div><Button onClick={() => openConfiguration()}><Plus className="mr-2 h-4 w-4" />Novo modelo</Button></div>
        <div className="space-y-2">{filteredConfigurations.map((template: any) => <Card key={template.id} className={template.active === false || template.active === 0 ? "opacity-60" : ""}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="flex items-center gap-2 font-medium"><Settings2 className="h-4 w-4 text-teal-600" />{template.description}</p><div className="mt-2 flex flex-wrap gap-1.5"><Badge variant="secondary">{template.category || "Configuração"}</Badge>{!template.modules?.length && !template.scopeItemKeys?.length && <Badge variant="outline">Projeto inteiro</Badge>}{template.modules?.map((module: string) => <Badge key={module} variant="outline">Módulo: {module}</Badge>)}{template.scopeItemKeys?.map((key: string) => <Badge key={key} className="bg-blue-50 text-blue-800">Scope: {key}</Badge>)}</div></div><Button variant="outline" size="sm" onClick={() => openConfiguration(template)}><Pencil className="mr-2 h-3.5 w-3.5" />Editar</Button></CardContent></Card>)}{filteredConfigurations.length === 0 && <Empty label="Nenhum modelo de configuração encontrado." />}</div>
      </TabsContent>
    </Tabs>

    <Dialog open={activityOpen} onOpenChange={setActivityOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{editingActivityId ? "Editar atividade padrão" : "Nova atividade padrão"}</DialogTitle></DialogHeader><div className="grid gap-4">
      <div><Label>Título *</Label><Input value={activityForm.title} onChange={event => setActivityForm(form => ({ ...form, title: event.target.value }))} /></div><div><Label>Descrição</Label><Textarea value={activityForm.description} onChange={event => setActivityForm(form => ({ ...form, description: event.target.value }))} /></div>
      <div className="grid gap-3 sm:grid-cols-3"><FieldSelect label="Prioridade" value={activityForm.priority} values={priorities.map(value => ({ value, label: value }))} onChange={value => setActivityForm(form => ({ ...form, priority: value as ActivityPriority }))} /><FieldSelect label="Fase da Trilha do GP" value={activityForm.gpPhase} values={gpPhases.map(value => ({ value, label: value }))} onChange={value => setActivityForm(form => ({ ...form, gpPhase: value as ActivityForm["gpPhase"] }))} /><FieldSelect label="Papel responsável" value={activityForm.ownerRole} values={Object.entries(roleLabels).map(([value, label]) => ({ value, label }))} onChange={value => setActivityForm(form => ({ ...form, ownerRole: value as ActivityTemplateOwnerRole }))} /></div>
      <div className="grid gap-3 sm:grid-cols-2"><FieldSelect label="Recorrência" value={activityForm.recurrence} values={[{ value: "none", label: "Não recorrente" }, { value: "weekly", label: "Semanal" }, { value: "monthly", label: "Mensal" }]} onChange={value => setActivityForm(form => ({ ...form, recurrence: value as ActivityTemplateRecurrence }))} /><label className="flex items-end gap-2 rounded-md border p-3"><Switch checked={activityForm.required} onCheckedChange={required => setActivityForm(form => ({ ...form, required }))} /><span className="text-sm font-medium">{activityForm.required ? "Atividade obrigatória" : "Atividade opcional"}</span></label></div>
      {activityForm.recurrence === "none" && <div><Label>Dias após o início do projeto</Label><Input type="number" min={0} max={3650} value={activityForm.dueOffsetDays} onChange={event => setActivityForm(form => ({ ...form, dueOffsetDays: Number(event.target.value) }))} /></div>}{activityForm.recurrence === "weekly" && <FieldSelect label="Dia de vencimento" value={String(activityForm.weekday)} values={weekdays.map(day => ({ value: String(day.value), label: day.label }))} onChange={value => setActivityForm(form => ({ ...form, weekday: Number(value) }))} />}{activityForm.recurrence === "monthly" && <div><Label>Dia do mês</Label><Input type="number" min={1} max={31} value={activityForm.monthDay} onChange={event => setActivityForm(form => ({ ...form, monthDay: Number(event.target.value) }))} /></div>}
      <label className="flex items-center gap-2"><Switch checked={activityForm.appliesToAllProjects} onCheckedChange={appliesToAllProjects => setActivityForm(form => ({ ...form, appliesToAllProjects }))} /><span className="text-sm font-medium">Aplicar a todos os projetos</span></label>
      <div className="space-y-2"><Label>Projetos e responsáveis</Label><div className="max-h-72 space-y-2 overflow-y-auto rounded-md border p-2">{activityOptions.map(option => { const selected = activityForm.appliesToAllProjects || activityForm.selectedProjectIds.includes(option.project.id); const assignment = activityForm.projects.find(item => item.projectId === option.project.id)?.assigneeUserId || ""; const candidates = option.candidates.filter(candidate => activityForm.ownerRole === "manager" || candidate.role === activityForm.ownerRole); return <div key={option.project.id} className="grid gap-2 rounded-md border p-2 sm:grid-cols-[1fr_240px]"><label className="flex items-center gap-2 text-sm"><Checkbox disabled={activityForm.appliesToAllProjects} checked={selected} onCheckedChange={() => setActivityForm(form => ({ ...form, selectedProjectIds: toggle(form.selectedProjectIds, option.project.id) }))} />{option.project.name}</label><Select disabled={!selected} value={assignment || "fallback"} onValueChange={value => setActivityForm(form => ({ ...form, projects: [...form.projects.filter(item => item.projectId !== option.project.id), { projectId: option.project.id, assigneeUserId: value === "fallback" ? "" : value }] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fallback">Automático / GP</SelectItem>{candidates.map(candidate => <SelectItem key={candidate.id} value={candidate.id}>{candidate.name}</SelectItem>)}</SelectContent></Select></div>; })}</div></div>
    </div><DialogFooter><Button variant="outline" onClick={() => setActivityOpen(false)}>Cancelar</Button><Button onClick={saveActivity} disabled={!activityForm.title.trim() || (!activityForm.appliesToAllProjects && !activityForm.selectedProjectIds.length) || createActivity.isPending || updateActivity.isPending}>Salvar</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={bdcqOpen} onOpenChange={setBdcqOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{bdcqForm.id ? "Editar pergunta padrão" : "Nova pergunta padrão"}</DialogTitle></DialogHeader><div className="grid gap-4"><div><Label>Pergunta *</Label><Textarea rows={4} value={bdcqForm.question} onChange={event => setBdcqForm(form => ({ ...form, question: event.target.value }))} /></div><div><Label>Categoria</Label><Input value={bdcqForm.category} onChange={event => setBdcqForm(form => ({ ...form, category: event.target.value }))} /></div><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2"><Switch checked={bdcqForm.required} onCheckedChange={required => setBdcqForm(form => ({ ...form, required }))} /><span className="text-sm font-medium">Obrigatória</span></label><label className="flex items-center gap-2"><Switch checked={bdcqForm.active === 1} onCheckedChange={active => setBdcqForm(form => ({ ...form, active: active ? 1 : 0 }))} /><span className="text-sm font-medium">Ativa</span></label></div><div><Label>Módulos relacionados</Label><div className="mt-2 flex flex-wrap gap-2">{moduleOptions.map(module => <Button key={module} type="button" size="sm" variant={bdcqForm.modules.includes(module) ? "default" : "outline"} onClick={() => setBdcqForm(form => ({ ...form, modules: toggle(form.modules, module) }))}>{module}</Button>)}</div></div><div><Label>Scope items relacionados</Label><div className="mt-2 max-h-64 space-y-1 overflow-y-auto rounded-md border p-2">{bdcqOptions.map(item => <label key={`${item.module}:${item.key}`} className="flex cursor-pointer items-center gap-2 rounded p-1.5 text-sm hover:bg-muted"><Checkbox checked={bdcqForm.scopeItemKeys.includes(item.key)} onCheckedChange={() => setBdcqForm(form => ({ ...form, scopeItemKeys: toggle(form.scopeItemKeys, item.key) }))} /><span>{item.code ? `${item.code} - ` : ""}{item.name}</span><Badge variant="outline" className="ml-auto">{item.module}</Badge></label>)}</div><p className="mt-1 text-xs text-muted-foreground">Sem módulos e scope items, a pergunta será geral. Com ambos, o projeto deve corresponder aos dois.</p></div></div><DialogFooter><Button variant="outline" onClick={() => setBdcqOpen(false)}>Cancelar</Button><Button onClick={saveBdcq} disabled={!bdcqForm.question.trim() || createBdcq.isPending || updateBdcq.isPending}>Salvar</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={configurationOpen} onOpenChange={setConfigurationOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{configurationForm.id ? "Editar modelo de configuração" : "Novo modelo de configuração"}</DialogTitle></DialogHeader><div className="grid gap-4"><div><Label>Passo de configuração *</Label><Textarea rows={4} value={configurationForm.description} onChange={event => setConfigurationForm(form => ({ ...form, description: event.target.value }))} placeholder="Descreva o fluxo ou passo padrão a executar" /></div><div><Label>Categoria</Label><Input value={configurationForm.category} onChange={event => setConfigurationForm(form => ({ ...form, category: event.target.value }))} /></div><label className="flex items-center gap-2"><Switch checked={configurationForm.active} onCheckedChange={active => setConfigurationForm(form => ({ ...form, active }))} /><span className="text-sm font-medium">Modelo ativo</span></label><div><Label>Aplicar aos módulos</Label><div className="mt-2 flex flex-wrap gap-2">{moduleOptions.map(module => <Button key={module} type="button" size="sm" variant={configurationForm.modules.includes(module) ? "default" : "outline"} onClick={() => setConfigurationForm(form => ({ ...form, modules: toggle(form.modules, module) }))}>{module}</Button>)}</div></div><div><Label>Aplicar aos scope items</Label><div className="mt-2 max-h-64 space-y-1 overflow-y-auto rounded-md border p-2">{bdcqOptions.map(item => <label key={`${item.module}:${item.key}`} className="flex cursor-pointer items-center gap-2 rounded p-1.5 text-sm hover:bg-muted"><Checkbox checked={configurationForm.scopeItemKeys.includes(item.key)} onCheckedChange={() => setConfigurationForm(form => ({ ...form, scopeItemKeys: toggle(form.scopeItemKeys, item.key) }))} /><span>{item.code ? `${item.code} - ` : ""}{item.name}</span><Badge variant="outline" className="ml-auto">{item.module}</Badge></label>)}</div><p className="mt-1 text-xs text-muted-foreground">Sem módulo ou scope item, o passo será aplicado uma vez ao projeto inteiro.</p></div></div><DialogFooter><Button variant="outline" onClick={() => setConfigurationOpen(false)}>Cancelar</Button><Button onClick={saveConfiguration} disabled={!configurationForm.description.trim() || createConfiguration.isPending || updateConfiguration.isPending}>Salvar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Empty({ label }: { label: string }) { return <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">{label}</div>; }
function FieldSelect({ label, value, values, onChange }: { label: string; value: string; values: Array<{ value: string; label: string }>; onChange: (value: string) => void }) { return <div><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{values.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
