import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FlaskConical, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useWorkflowProject } from "./useWorkflowProject";

type TestType = "Unitário" | "Integrado";
type TestStatus = "Não iniciado" | "Em execução" | "Aprovado" | "Reprovado" | "Bloqueado";
const statuses: TestStatus[] = ["Não iniciado", "Em execução", "Aprovado", "Reprovado", "Bloqueado"];
const emptyForm = { type: "Unitário" as TestType, code: "", title: "", description: "", module: "", requirementId: "", scopeItemId: "", dcdId: "", preconditions: "", steps: "", expectedResult: "", responsible: "" };

export default function TestsPage() {
  const { projectId } = useWorkflowProject();
  const [typeFilter, setTypeFilter] = useState<"Todos" | TestType>("Todos");
  const [search, setSearch] = useState("");
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [executing, setExecuting] = useState<any>(null);
  const [execution, setExecution] = useState({ status: "Em execução" as TestStatus, actualResult: "", evidence: "", executedAt: new Date().toISOString().slice(0, 10) });
  const { data: tests = [], refetch } = trpc.workflow.tests.list.useQuery({ projectId });
  const { data: requirements = [] } = trpc.workflow.requirements.list.useQuery({ projectId });
  const { data: scopeItems = [] } = trpc.workflow.scopeItems.list.useQuery({ projectId });
  const { data: dcds = [] } = trpc.workflow.dcd.list.useQuery({ projectId });
  const { data: resources = [] } = trpc.resources.list.useQuery();
  const { data: lookups } = trpc.settings.getLookups.useQuery();
  const modules = (lookups?.fronts || []).filter((item: any) => item.active).map((item: any) => item.value);
  const create = trpc.workflow.tests.create.useMutation({ onSuccess: () => { refetch(); setShowAdd(false); setForm(emptyForm); toast.success("Caso de teste criado"); }, onError: error => toast.error(error.message) });
  const update = trpc.workflow.tests.update.useMutation({ onSuccess: () => { refetch(); setExecuting(null); toast.success("Execução registrada"); }, onError: error => toast.error(error.message) });
  const remove = trpc.workflow.tests.delete.useMutation({ onSuccess: () => { refetch(); toast.success("Caso de teste removido"); }, onError: error => toast.error(error.message) });
  const visible = tests.filter((item: any) => (typeFilter === "Todos" || item.type === typeFilter) && [item.code, item.title, item.module, item.responsible].some(value => String(value || "").toLowerCase().includes(search.toLowerCase())));
  const approved = tests.filter((item: any) => item.status === "Aprovado").length;
  const failed = tests.filter((item: any) => item.status === "Reprovado").length;
  const openExecution = (item: any) => { setExecuting(item); setExecution({ status: item.status || "Em execução", actualResult: item.actualResult || "", evidence: item.evidence || "", executedAt: item.executedAt || new Date().toISOString().slice(0, 10) }); };
  return <div className="space-y-4 p-3 sm:p-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><FlaskConical className="h-6 w-6" />Testes</h1><p className="text-sm text-muted-foreground">Planejamento e execução de testes unitários e integrados</p></div><Button onClick={() => setShowAdd(true)}><Plus className="mr-2 h-4 w-4" />Novo caso de teste</Button></div>
    <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="py-4"><p className="text-xs text-muted-foreground">Total</p><p className="text-2xl font-bold">{tests.length}</p></CardContent></Card><Card><CardContent className="py-4"><p className="text-xs text-muted-foreground">Aprovados</p><p className="text-2xl font-bold text-emerald-600">{approved}</p></CardContent></Card><Card><CardContent className="py-4"><p className="text-xs text-muted-foreground">Reprovados</p><p className="text-2xl font-bold text-red-600">{failed}</p></CardContent></Card></div>
    <div className="flex flex-wrap gap-2"><Select value={typeFilter} onValueChange={value => setTypeFilter(value as typeof typeFilter)}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Todos">Todos os tipos</SelectItem><SelectItem value="Unitário">Unitários</SelectItem><SelectItem value="Integrado">Integrados</SelectItem></SelectContent></Select><div className="relative min-w-60 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar casos de teste..." value={search} onChange={event => setSearch(event.target.value)} /></div></div>
    <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Tipo</TableHead><TableHead>Caso de teste</TableHead><TableHead>Responsável</TableHead><TableHead>Status</TableHead><TableHead className="w-24" /></TableRow></TableHeader><TableBody>{visible.length === 0 ? <TableRow><TableCell colSpan={6} className="py-8 text-center text-muted-foreground">Nenhum caso de teste cadastrado.</TableCell></TableRow> : visible.map((item: any) => <TableRow key={item.id}><TableCell className="font-mono text-xs">{item.code || "-"}</TableCell><TableCell><Badge variant={item.type === "Integrado" ? "default" : "outline"}>{item.type}</Badge></TableCell><TableCell><p className="font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.module || "Sem módulo"}</p></TableCell><TableCell>{item.responsible || "-"}</TableCell><TableCell><Badge variant={item.status === "Aprovado" ? "default" : item.status === "Reprovado" ? "destructive" : "secondary"}>{item.status}</Badge></TableCell><TableCell><div className="flex"><Button size="icon" variant="ghost" title="Registrar execução" onClick={() => openExecution(item)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => remove.mutate({ id: item.id })}><Trash2 className="h-4 w-4" /></Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Dialog open={showAdd} onOpenChange={setShowAdd}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Novo caso de teste</DialogTitle></DialogHeader><div className="grid gap-3">
      <div className="grid gap-3 sm:grid-cols-3"><div><Label>Tipo</Label><Select value={form.type} onValueChange={type => setForm(current => ({ ...current, type: type as TestType }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Unitário">Unitário</SelectItem><SelectItem value="Integrado">Integrado</SelectItem></SelectContent></Select></div><div><Label>Código</Label><Input value={form.code} onChange={event => setForm(current => ({ ...current, code: event.target.value }))} placeholder="TU-001" /></div><div><Label>Módulo</Label><Select value={form.module || "none"} onValueChange={module => setForm(current => ({ ...current, module: module === "none" ? "" : module }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem módulo</SelectItem>{modules.map((module: string) => <SelectItem key={module} value={module}>{module}</SelectItem>)}</SelectContent></Select></div></div>
      <div><Label>Título *</Label><Input value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))} /></div><div><Label>Descrição</Label><Textarea value={form.description} onChange={event => setForm(current => ({ ...current, description: event.target.value }))} /></div>
      <div className="grid gap-3 sm:grid-cols-3"><div><Label>Requisito</Label><Select value={form.requirementId || "none"} onValueChange={requirementId => setForm(current => ({ ...current, requirementId: requirementId === "none" ? "" : requirementId }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{requirements.map((item: any) => <SelectItem key={item.id} value={item.id}>{item.code || item.title}</SelectItem>)}</SelectContent></Select></div><div><Label>Scope Item</Label><Select value={form.scopeItemId || "none"} onValueChange={scopeItemId => setForm(current => ({ ...current, scopeItemId: scopeItemId === "none" ? "" : scopeItemId }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{scopeItems.map((item: any) => <SelectItem key={item.id} value={item.id}>{item.code || item.name}</SelectItem>)}</SelectContent></Select></div><div><Label>DCD</Label><Select value={form.dcdId || "none"} onValueChange={dcdId => setForm(current => ({ ...current, dcdId: dcdId === "none" ? "" : dcdId }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{dcds.map((item: any) => <SelectItem key={item.id} value={item.id}>{item.title}</SelectItem>)}</SelectContent></Select></div></div>
      <div><Label>Pré-condições</Label><Textarea value={form.preconditions} onChange={event => setForm(current => ({ ...current, preconditions: event.target.value }))} /></div><div><Label>Passos do teste</Label><Textarea rows={5} value={form.steps} onChange={event => setForm(current => ({ ...current, steps: event.target.value }))} placeholder="1. ...\n2. ..." /></div><div><Label>Resultado esperado</Label><Textarea value={form.expectedResult} onChange={event => setForm(current => ({ ...current, expectedResult: event.target.value }))} /></div><div><Label>Responsável</Label><Select value={form.responsible || "none"} onValueChange={responsible => setForm(current => ({ ...current, responsible: responsible === "none" ? "" : responsible }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Não atribuído</SelectItem>{resources.map((resource: any) => <SelectItem key={resource.id} value={resource.name}>{resource.name}</SelectItem>)}</SelectContent></Select></div>
    </div><DialogFooter><Button onClick={() => create.mutate({ projectId, ...form })} disabled={!form.title.trim() || create.isPending}>Criar caso de teste</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!executing} onOpenChange={open => { if (!open) setExecuting(null); }}><DialogContent><DialogHeader><DialogTitle>Registrar execução — {executing?.title}</DialogTitle></DialogHeader><div className="grid gap-3"><div><Label>Status</Label><Select value={execution.status} onValueChange={status => setExecution(current => ({ ...current, status: status as TestStatus }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{statuses.map(status => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></div><div><Label>Resultado obtido</Label><Textarea rows={5} value={execution.actualResult} onChange={event => setExecution(current => ({ ...current, actualResult: event.target.value }))} /></div><div><Label>Evidência ou referência</Label><Input value={execution.evidence} onChange={event => setExecution(current => ({ ...current, evidence: event.target.value }))} placeholder="URL, ticket, arquivo ou observação" /></div><div><Label>Data de execução</Label><Input type="date" value={execution.executedAt} onChange={event => setExecution(current => ({ ...current, executedAt: event.target.value }))} /></div></div><DialogFooter><Button onClick={() => update.mutate({ id: executing.id, data: execution })} disabled={update.isPending}>Salvar execução</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
