export type BdcqTemplate = { module: string; category: string; question: string };

export const BDCQ_TEMPLATES: BdcqTemplate[] = [
  { module: "SD", category: "Pricing", question: "Quais tipos de condição de preço são utilizados?" },
  { module: "SD", category: "Sales Order", question: "Quais tipos de pedido de venda e fluxos de aprovação são necessários?" },
  { module: "SD", category: "Delivery", question: "Como funciona o processo de expedição e quais exceções existem?" },
  { module: "SD", category: "Billing", question: "Quais tipos de faturamento e regras de cancelamento são utilizados?" },
  { module: "MM", category: "Purchasing", question: "Quais tipos de pedido de compra são utilizados?" },
  { module: "MM", category: "Purchasing", question: "Quais alçadas e estratégias de liberação de compras são necessárias?" },
  { module: "MM", category: "Inventory", question: "Quais movimentos, depósitos e controles de estoque são utilizados?" },
  { module: "MM", category: "Invoice Verification", question: "Como funciona a verificação de faturas e suas tolerâncias?" },
  { module: "FI", category: "General Ledger", question: "Qual plano de contas e quais princípios contábeis serão utilizados?" },
  { module: "FI", category: "Accounts Payable", question: "Quais condições e métodos de pagamento são praticados?" },
  { module: "FI", category: "Accounts Receivable", question: "Como funcionam cobrança, crédito e conciliação de clientes?" },
  { module: "FI", category: "Tax", question: "Quais impostos e motores fiscais incidem nas operações?" },
  { module: "CO", category: "Cost Center", question: "Qual a estrutura de centros de custo e ciclos de rateio?" },
  { module: "CO", category: "Profit Center", question: "Qual a estrutura de centros de lucro e segmentação gerencial?" },
  { module: "CO", category: "Controlling", question: "Quais fechamentos, alocações e relatórios gerenciais são necessários?" },
  { module: "PP", category: "Planning", question: "Como são executados previsão, MRP e planejamento de capacidade?" },
  { module: "PP", category: "Production", question: "Quais tipos de ordem e estratégias de produção são utilizados?" },
  { module: "PP", category: "Master Data", question: "Como serão mantidas listas técnicas, roteiros e versões de produção?" },
  { module: "WM", category: "Warehouse", question: "Quais estruturas de depósito, estratégias de entrada e retirada são necessárias?" },
  { module: "EWM", category: "Warehouse", question: "Quais processos inbound, outbound e internos serão executados no EWM?" },
  { module: "QM", category: "Quality", question: "Quais tipos de inspeção e planos de controle de qualidade são necessários?" },
  { module: "PM", category: "Maintenance", question: "Quais estratégias, planos e ordens de manutenção são utilizados?" },
  { module: "PS", category: "Projects", question: "Como serão estruturados projetos, EAP, redes, orçamento e apropriações?" },
  { module: "HCM", category: "People", question: "Quais estruturas organizacionais e integrações de dados de pessoas são necessárias?" },
  { module: "BASIS", category: "Technical", question: "Quais ambientes, integrações, perfis e requisitos não funcionais devem ser atendidos?" },
];
